a = input('Digite Algo: ')
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaços?', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfanúmerico? ', a.isalnum())
print('É alfabético? ', a.isalpha())
print('Está em Maiusculas?', a.isupper())
print('Está em minúscula? ', a.islower())
print('Está capitalizada? ', a.istitle())
